### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by froblesmartin** [atlassian/gajira-cli#26]
Hi! I was checking this and considering using it, but checking what it uses, the CLI is https://github.com/go-jira/jira, and it also seems to be abandoned 😞 , it is not even an official CLI from Atlassian, even though this GitHub Action is from you.

Could you please let us know if this is still going to be maintained? And if you have any plan about the CLI tool to use?

**Comment by bgvozdev** [comment]
Hi @froblesmartin , unfortunately we’re don't have any current plans to continue maintaining it.

**Comment by froblesmartin** [comment]
Hi @bgvozdev ! Thanks a lot for answering! :) What do you think then about opening a PR to add a note at the beginning of the README? Or archiving the repo for now? 🤔

**Comment by bgvozdev** [comment]
@froblesmartin added a big and scary warning icon, hope that would to :)
